This notebook is for evaluating sample psv data from https://www.ncei.noaa.gov/

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import pyarrow as pa
import pyarrow.parquet as pq

In [3]:
df = pd.read_csv('GHCNh_AQC00914594_2021.psv', sep='|')

In [4]:
df.head()

,Station_ID,Station_name,Year,Month,Day,Hour,Minute,Latitude,Longitude,Elevation,...,sky_cover_baseht_3_Quality_Code,sky_cover_baseht_3_Report_Type,sky_cover_baseht_3_Source_Code,sky_cover_baseht_3_Source_Station_ID,remarks,remarks_Measurement_Code,remarks_Quality_Code,remarks_Report_Type,remarks_Source_Code,remarks_Source_Station_ID
0,AQC00914594,MALAELOA,2021,1,1,0,0,-14.3333,-170.7667,42.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AQC00914594,MALAELOA,2021,1,1,1,0,-14.3333,-170.7667,42.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AQC00914594,MALAELOA,2021,1,1,2,0,-14.3333,-170.7667,42.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AQC00914594,MALAELOA,2021,1,1,3,0,-14.3333,-170.7667,42.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AQC00914594,MALAELOA,2021,1,1,4,0,-14.3333,-170.7667,42.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN